name: Update Database from Wikipedia
on: [workflow_dispatch]
jobs:
  Fetch-Wikipedia:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"
      - run: yarn install
      - run: yarn extract
